### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [DesignKapitein/prj-rev-bwfs-dasmoto#3]
Overall, great job! You structured your code in a clear and concise way, and practiced good (HTML) typing habits except for using the strong tag. The main reason why it is important to note the difference between the strong and b(old) tags is mostly so that others who are reading your code, perhaps to extend it, will know exactly what a string of text is meant to be interpreted as. Text surrounded by a strong tags means that text is very important and the reader's of the site must be able to see it. Text surrounded by a b(old) tag is more for making things pop out, to help with the design of the page. 

Good job!

**Comment by DesignKapitein** [comment]
Well thank you Aerodlyn! Now I really understand the difference between the <strong< and <b> tag. So the 'Strong tag has semantic value' where the 'bold tag just makes some things pop out'.

Is it ment for me to adjust the code so I pass this section or is it fine this way?

Thank you :D

**Comment by Aerodlyn** [comment]
I believe it is fine, since you have what you were supposed to create. I'm just here to provide some constructive criticism and good practices. :)
